[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "requests-cacher"
version = "0.1.0"
description = "Wrapper over `requests` package to cache api get requests in sqlite."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
